SELECT * FROM HR.EMPLOYEES;

-- 1. grouping by department ids and counting the employees by department wise, aggregation at department id
SELECT
    DEPARTMENT_ID,
    COUNT(*) AS TOTAL_EMPLOYESS
FROM
    HR.EMPLOYEES
GROUP BY
    DEPARTMENT_ID;

-- 2. calculating average salary of employees in each department, aggregation at department id
SELECT
    DEPARTMENT_ID,
    AVG(SALARY)
FROM
    HR.EMPLOYEES
GROUP BY
    DEPARTMENT_ID;

-- 3. calculating max and min salary of each department, aggregation at department id
SELECT
    DEPARTMENT_ID,
    MIN(SALARY) AS MIN_SALARY,
    MAX(SALARY) AS MAX_SALARY
FROM
    HR.EMPLOYEES
GROUP BY
    DEPARTMENT_ID
ORDER BY
    DEPARTMENT_ID;

-- 4. calculating total salaries for each departments, aggregation at department id
SELECT
    DEPARTMENT_ID,
    SUM(SALARY) AS TOTAL_SALARY
FROM
    HR.EMPLOYEES
GROUP BY
    DEPARTMENT_ID;

-- 5. calculating total emplyess and grouping by job wise, aggregation at job level
SELECT
    JOB_ID,
    COUNT(*) AS TOTAL_EMPLOYESES
FROM
    HR.EMPLOYEES
GROUP BY
    JOB_ID;

-- 6. calculating the avg salary for job wise, aggregation at job level
SELECT
    JOB_ID,
    AVG(SALARY) AS AVG_SALARY
FROM
    HR.EMPLOYEES
GROUP BY
    JOB_ID;

-- 7. calculating max salary for job wise
SELECT
    JOB_ID,
    MAX(SALARY) AS MAX_SALARY
FROM
    HR.EMPLOYEES
GROUP BY
    JOB_ID;

-- 8. calculating min salary for job wise
SELECT
    JOB_ID,
    MIN(SALARY) AS MIN_SALARY
FROM
    HR.EMPLOYEES
GROUP BY
    JOB_ID;

-- 9. calculating total salary paid for each job role
SELECT
    JOB_ID,
    SUM(SALARY) AS JOB_WISE_SALARY
FROM
    HR.EMPLOYEES
GROUP BY
    JOB_ID;

-- 10.Count the number of employees hired in each year

SELECT
    EXTRACT(YEAR FROM HIRE_DATE) AS YEAR,
    COUNT(*)                     AS TOTAL_EMPLOYEES_HIRED
FROM
    HR.EMPLOYEES
GROUP BY
    YEAR;



---------------------------------------------------------------------------------------------------------------------------
-- # Oracle SQL Aggregation Questions for Sales History Table
SELECT
    *
FROM
    SH.SALES;

-- 1. Count the number of sales transactions for each product.  
SELECT
    PROD_ID,
    COUNT(*)
FROM
    SH.SALES
GROUP BY
    PROD_ID;

-- 2. Find the average sale amount for each product.  
SELECT
    PROD_ID,
    AVG(AMOUNT_SOLD) AS AVG_SALE_AMOUNT
FROM
    SH.SALES
GROUP BY
    PROD_ID;

-- 3. Find the maximum and minimum sale amount for each product.  
SELECT
    PROD_ID,
    MAX(AMOUNT_SOLD) AS MAX_SALE_AMOUNT,
    MIN(AMOUNT_SOLD) AS MIN_SALE_AMOUNT
FROM
    SH.SALES
GROUP BY
    PROD_ID;

-- 4. Find the total revenue generated by each product.  
SELECT
    PROD_ID,
    SUM(AMOUNT_SOLD) AS TOTAL_REVENUE
FROM
    SH.SALES
GROUP BY
    PROD_ID;

-- 5. Count the number of sales transactions for each customer.  
SELECT
    CUST_ID,
    COUNT(AMOUNT_SOLD)
FROM
    SH.SALES
GROUP BY
    CUST_ID;

-- 6. Find the average sale amount per customer.  
SELECT
    CUST_ID,
    SUM(AMOUNT_SOLD)
FROM
    SH.SALES
GROUP BY
    CUST_ID;

-- 7. Find the highest purchase amount for each customer.  
SELECT
    CUST_ID,
    MAX(AMOUNT_SOLD)
FROM
    SH.SALES
GROUP BY
    CUST_ID;

-- 8. Find the lowest purchase amount for each customer.  
SELECT
    CUST_ID,
    MIN(AMOUNT_SOLD)
FROM
    SH.SALES
GROUP BY
    CUST_ID;

-- 9. Find the total revenue generated by each store location.  











